---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml

  - service.yml
  - deployment.yml

commonLabels:
  app.kubernetes.io/name: drone
  app.kubernetes.io/component: server

images:
  - name: drone-server
    newName: drone/drone
    newTag: "2.20"

configMapGenerator:
  - name: drone-server
    literals:
      - DRONE_SERVER_PORT=:8080

      - DRONE_CLEANUP_DISABLED=false
      - DRONE_CRON_DISABLED=false
      - DRONE_RUNNER_LOCAL=false
      - DRONE_JSONNET_ENABLED=true
      - DRONE_STARLARK_ENABLED=true
      - DRONE_PROMETHEUS_ANONYMOUS_ACCESS=true

...
